#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

# check that we are being run from the console
if ! expr "`tty`" : '^/dev/tty[0-9]$' >/dev/null; then
  echo "Must be run from console"
  exit 1
fi

newworld=0

if [ -f /proc/cpuinfo ]; then
  if grep pmac-generation'.*'NewWorld /proc/cpuinfo >/dev/null 2>/dev/null; then
    newworld=1
  fi
fi

if [ $newworld = 1 ]; then
  nvsetenv boot-device "hd:,\\:tbxi"
else
  nvsetenv boot-device /AAPL,ROM
  nvsetenv real-base ffffffff
fi

exec shutdown -t 1 -r now
